### ISSUE TITLE
about testing fps

### ISSUE THREAD

**Issue by mzy97** [MrEliptik/HandPose#10]
Thanks for your great work!
when running your code, i encounter some problem:

My os is win10, intel core i5-6500 CPU, 3.2GHZ, 8GB. And I'm using Intel Realsense camera to stream color images. Is this fps resonable? How should I boost the speed? 

thank you！

**Comment by MrEliptik** [comment]
Hi, thank you for your interest in this project. 
You forgot to write the actual performance you have (FPS number). Depending on your application, detection above 20 FPS can be considered near real time.

The most intensive and thus time-consuming task is the SSD inference to detect hands. Two things that could be done are **pruning** and **quantizing** the network. 

- **Quantization** is the act of using less bit to represent the weights. Right now, 32 bits floating points are used. I think you could drop to int8 or int16 without too much loss in precision.
- **Pruning** is the act of remove unused connections between neurons. This can greatly reduce the size of the network and thus increase speed.  

These two techniques combined could dramatically improve the inference speed.

**Comment by mzy97** [comment]
sorry, I forgot to write fps information
The actual fps on my computer is 3fps.
I don't install tensorflow from source, just using pip to install. Will this issue have such big impact.
Or, any other reason will contribute to this 3fps performance?

thank you

**Comment by mzy97** [comment]
your readme shows this code can run at 25fps with visualization. how you achieve it?
what's your environment, configuration and hardware?

thank you

**Comment by MrEliptik** [comment]
I'm also using Tensorflow installed with pip. The performance I've mentioned were achieved with an intel i5-8300H running at 4Ghz, on both windows and linux with the default parameters for *Handpose.py* (**4 workers, display=true, image size 300x200.**)

When not compiled from source, you're missing some CPU optimization, but I don't think it would make such a huge difference.

I see that your CPU has 4 cores, how many threads are you using ? You can specify the number of threads with the parameters `--num-workers`, by default it's at 4 and it's what I was using. Your CPU clocks at 3.2Ghz, even though it's not 4Ghz like mine it shouldn't make that huge of a difference. You might want to check the power mode you're using on your computer, make sure it's performance, and that you're hitting the 3.2Ghz. 

If you've checked all of that and it's still very low in performance, you can try removing the display by passing `--display=0` and/or using a smaller input size with `--width` and `--height`. Make sure to use a supported width and height, as it's not resizing, but the actual resolution at which the camera is going to capture frames.
