### ISSUE TITLE
[ WARN:0] videoio(MSMF): can't grab frame. 

### ISSUE THREAD

**Issue by Priyanka-M96** [MrEliptik/HandPose#17]
When I try to run the program according to the given instruction. The following error is thrown. 

`Using TensorFlow backend.
[ WARN:0] videoio(MSMF): can't grab frame. Error: -2147483638
320.0 180.0
{'im_width': 320.0, 'im_height': 180.0, 'score_thresh': 0.18, 'num_hands_detect': 1} Namespace(display=1, fps=1, height=200, num_hands=1, num_workers=4, queue_size=5, video_source=0, width=300)
Four
Garbage
Rock
Startrek
Fist
Palm
`

please can I know the solution for this problem.
Thanking in advance

**Comment by MrEliptik** [comment]
Did you solve it? It seems like a resolution error.

**Comment by Priyanka-M96** [comment]
It was the error with python version. python 3.6 is required
