### ISSUE TITLE
Tensorflow 2.1

### ISSUE THREAD

**Issue by jasonmarziani** [MrEliptik/HandPose#19]
Hey, thanks for sharing this project.  Any advice on getting this up and running with Tensorflow 2.1?  Switching the import prompt across the various files still results in a number of errors.

**Comment by MrEliptik** [comment]
Tensorflow 2 is a redesign of the API so it breaks comparability with a lot of 1.X methods. You could try using 
```
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
```
See more at https://www.tensorflow.org/guide/migrate.

Anyway, if you want to make a PR with the compatibility, I'd gladly appreciate it.
