### ISSUE TITLE
Unable to run code

### ISSUE THREAD

**Issue by mmsszzz** [MrEliptik/HandPose#23]
The model can be loaded normally, and the camera can be opened, but the running result is gray without pattern
![987452F92799A163AE08AFA7E3423E4F](https://user-images.githubusercontent.com/80474838/110816569-6ab03380-82c6-11eb-83bd-a7c40cce0d4a.png)
![B527610564F1BA630E241B0E3366D9D2](https://user-images.githubusercontent.com/80474838/110816578-6c79f700-82c6-11eb-98ff-67d689460ebc.jpg)

**Comment by MrEliptik** [comment]
From what I'm seeing the frame seems to be empty. You need to make sure openCV is using the right camera, and can access the result frame. 

You can test it with the following code

    import numpy as np
    import cv2

    cap = cv2.VideoCapture(0)

    while(True):
        # Capture frame-by-frame
        ret, frame = cap.read()

        # Our operations on the frame come here
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        # Display the resulting frame
        cv2.imshow('frame',gray)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    # When everything done, release the capture
    cap.release()
    cv2.destroyAllWindows()
