### ISSUE TITLE
Poses Folder

### ISSUE THREAD

**Issue by vinceliu21** [MrEliptik/HandPose#4]
Great repo! One question though. Everything is working well, but I want to add an image and retrain the model. However I see that the Poses folder is not in the repository. How can I retrain the model without the data? Is there a place to get the Poses data folder. Thank you!

**Comment by MrEliptik** [comment]
Yes ofc I forgot to add a link to the dataset. I can provide you with the link tonight. It's not the exact dataset used for training as I lost part of it.. but it's still something. 
Also if you juste add a Poses folder to your repo, you could use Addpose.py to add your own pose.

**Comment by MrEliptik** [comment]
Also, if you want, I think you could try to use transfer learning to add new poses. I'm not sure of how good would be the results but it's something I wanted to try. It makes the process of adding a pose faster and less painful.

**Comment by MrEliptik** [comment]
@vinceliu21 Here is the link to the Poses compressed as .tar.gz. Don't hesitate if you have any trouble. The data is already cleaned and resized to 28x28. You can do it to your own data using normalize.py
http://www.mediafire.com/file/wt7dc5e9jgnym04/Poses.tar.gz/file

**Comment by vinceliu21** [comment]
Great @MrEliptik , thank you. And yes, I plan to look into doing transfer learning as well. I also have thought about just retraining the model to support two classes. Fist and palm to represent open and close. Everything else would be garbage. So then I can just use your AddPose.py scripts. I would also need to modify the HandPose.txt file which defines the classes correct?

**Comment by MrEliptik** [comment]
If I recall correctly when you add a new pose it gets added to the .txt file. But if you remove, or rearrange classes you have to fix it yourself yes.
