### ISSUE TITLE
images with 2 hands

### ISSUE THREAD

**Issue by BUlexlab** [MrEliptik/HandPose#8]
I want to use this on images which sometimes have two hands, which may or may not have separate shapes.
What would I need to edit to make that work?

**Comment by MrEliptik** [comment]
You can pass the parameter `--num_hands` when calling **handpose.py** or edit _line 81_ and change `default=1` to `default=2`

**Comment by MrEliptik** [comment]
I'm closing as it's not an issue, but you can ask me anything if needed!
