### ISSUE TITLE
video saving issue and citation

### ISSUE THREAD

**Issue by BUlexlab** [MrEliptik/HandPose#9]
Hello,
Thank you for this great work! I'm looking to use this to add features to a classifier I'm developing for ASL phonology -- if we end up using this repository, how would you prefer to be cited in a paper?

Also, I'm running into a problem in retraining. When I use AddPose.py, after I record a video it says "processed 1 frame(s)" and when I look in the poses folder the .avi video is not readable and no images have been taken out from it. This causes errors when I try to run cnn.py. Any idea what could cause this? The AddPose script itself doesn't raise any errors. 

(I am using a slightly newer version on tensorflow, 1.13 not 1.12, but didn't think this should be a problem). I'm running a new macbook pro. 

```
`python3 AddPose.py 
/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.7
  return f(*args, **kwds)
Do you want to : 
 1 - Add new pose                             
 2 - Add examples to existing pose                             
 3 - Add garbage examples
1
Enter a name for the pose you want to add :
7
You'll now be prompted to record the pose you want to add. 
                 Please place your hand beforehand facing the camera, and press any key when ready. 
                 When finished press 'q'.

2019-05-20 09:52:32.689 Python[18449:46975865] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to (null)
>> loading frozen model..
> ====== loading HAND frozen graph into memory
2019-05-20 09:52:50.986901: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
>  ====== Hand Inference graph loaded.
>> model loaded!
   Processed 1 frames!`
```

EDIT:
I solved my issue with the video saving. The problem was that the default width and height on my machine were different from the hardcoded values. I fixed this by adding this line before the "out" assignment in AddPose:
```
`width = 0
    height = 0
    if cap.isOpened(): 
        width = int(cap.get(3))  # float
        height = int(cap.get(4)) # float`
```

**Comment by MrEliptik** [comment]
Hi, thanks for your interest! I'm not really familiar with how it's usually done, I think it's ok for me if you just cite my name with the link to this repo.

Glad you solved the issue! One thing I wanted to add was to get the camera parameters and the beginning of the script to avoid hard-coded value but I never did it. I you happen to make that kind of modification and want to create a PR you'd be welcomed!

Also, I'd be glad to have updates on your projects. Do not hesitate to send me info on twitter @VicMeunier or by email at victormeunier.dev@gmail.com
